spring:
  application:
    name: system-generator
  profiles:
    active: @environment@
server:
  port: 8889
mybatis-plus:
  type-aliases-package: com.yinlu.system.generator.model
  mapper-locations: classpath:mapper/*.xml
  global-config:
    banner: false
swagger:
  contact:
    name: "kuroneko"
    email: "dingdangmaoup@vip.qq.com"
    url: "https://kuroneko.fun"
  enabled: true
  base-package: com.yinlu.system.generator