spring:
  application:
    name: system-generator
#  datasource:
#    dynamic:
#      strict: false
  profiles:
    active: @environment@
customize:
  datasource:
    tableName: system_data_source
    url: jdbc:mysql://localhost:3306/system_center?serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8998
mybatis-plus:
  type-aliases-package: com.yinlu.system.generator.model
  mapper-locations: classpath:mapper/*.xml
  global-config:
    banner: false
swagger:
  contact:
    name: "kuroneko"
    email: "dingdangmaoup@vip.qq.com"
    url: "https://kuroneko.fun"